# Generated by Django 2.1.1 on 2018-11-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidnap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='upload/images')),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
