# Generated by Django 2.1.1 on 2018-11-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidnap', '0002_auto_20181112_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('audio', models.FileField(upload_to='upload/audios')),
            ],
            options={
                'db_table': 'Audio',
            },
        ),
    ]
