# Generated by Django 2.1.1 on 2018-11-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidnap', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
