# Generated by Django 2.1.1 on 2018-11-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidnap', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
